### ISSUE TITLE
Support path and query parameters

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#204]
Add support for routing path params and expose both path params and query params in screen scope.

**Comment by sagardspeed2** [comment]
@evshi 

we are adding the screen paths as per

```
screens: [
    {
      id: "menu",
      name: "Menu",
      content: String(MenuYAML),
    },
]
```

where, screen name become the route path, so to enhance the route functionality and support the path params, we need to add one more key to this object. something like this,

```
screens: [
    {
      id: "menu",
      name: "Menu",
      params: ["param1", "param2"]
      content: String(MenuYAML),
    },
]
```

or we can add one property with name of path, and refer that property as route path

```
screens: [
    {
      id: "menu",
      name: "Menu",
      path: "menu/:param1/:param2",
      content: String(MenuYAML),
    },
]
```

need your suggestions on this

**Comment by evshi** [comment]
@sagardspeed2 let's go with second option of adding optional path property to each screen

**Comment by sagardspeed2** [comment]
okay sure
