### ISSUE TITLE
Implement Search widget

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#23]
AC:

- Implement search view
- Can configure default text
- Specify data set to search over
- Optional: pick a search provider

![Image](https://user-images.githubusercontent.com/4132143/267730920-8c526bea-2d9c-4388-a082-34bb9bec07d2.png)

**Comment by evshi** [comment]
@anserwaseem can you please help close out this ticket from the open PR?

**Comment by anserwaseem** [comment]
Search enhancement ticket [here](https://github.com/EnsembleUI/ensemble-react/issues/96)
