### ISSUE TITLE
Implement Avatar widget

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#24]
AC:

- Display user image
- Configurable context menu shows up when clicking on it

![Image](https://user-images.githubusercontent.com/4132143/267731206-f1297579-cfcb-485b-ad58-bf3ddadd9fbb.png)

**Comment by vusters** [comment]
1. First come up with a Ensemble schema for this widget. Please follow https://mui.com/material-ui/react-avatar/
2. Implement the widget and update the schema
