### ISSUE TITLE
Expressions in one Screen break item-template data on another screen

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble-react#264]
**Describe the bug**
- when we have expressions in SideBar Widget, like for any color or fontSize etc. 
- This breaks the patients screen such that 
1. Every patient card shows same task info. as in SS ( before and after )
2. Then when i move to enrollment screen the patient details do not work anymore becuase a fucntion ( used for handling a task user select at SelectDOS ) break becuase task is no longer an array.

**To Reproduce**
Simply go to SideBar screen in atlas and change any widget style property like color, fontSize to an expression, then we can simply observe the issue as mentioned in description.

**Expected behavior**

**Screenshots**
https://media.discordapp.net/attachments/1106512057555226634/1187765969460924550/Screenshot_2023-12-22_at_7.34.53_PM.png?ex=65981442&is=65859f42&hm=4da9ff317c83dee4aa600e46c7e8852c52d0ce922f63b0da08ce6b5089285798&=&format=webp&quality=lossless&width=1348&height=982

https://media.discordapp.net/attachments/1106512057555226634/1187765969460924550/Screenshot_2023-12-22_at_7.34.53_PM.png?ex=65981442&is=65859f42&hm=4da9ff317c83dee4aa600e46c7e8852c52d0ce922f63b0da08ce6b5089285798&=&format=webp&quality=lossless&width=1348&height=982

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sagardspeed2** [comment]
Issue related nested item-template is not capturing the data from the parent customscopeprovider

**Comment by sibteali786** [comment]
Thanks for mentioning it here @sagardspeed2 i ll take it from here

**Comment by evshi** [comment]
Root cause is useTemplateData does not import custom scope. Similar issue with Chart config. @sibteali786 do you have scope to work on it? If not let's pass back to @sagardspeed2
