### ISSUE TITLE
Support import script in Global block

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#292]
**Is your feature request related to a problem? Please describe.**
We don't have javascript highlighting in YAML files. one way is to break out the javascript into a separate file and import it via yaml. This is already supported in executeCode function.

**Describe the solution you'd like**
Update the global block to also support scriptName and import file from app context

**Describe alternatives you've considered**

**Additional context**

**Comment by sagardspeed2** [comment]
@evshi, if we update the global block to support the script name, and then during runtime, import that script from the app context, the current implementation of the global scope, which accepts the code block in the form of a string, may break.

```
Global: |
  function callMeAsYouSee(){
    console.log("See ya, it works");
  }

  function manipulateData(dataArr){
    let newData = dataArr;
    console.log(dataArr);
  }
```

As per the evaluate function, it simply compiles the string of the global scope as code.

**Comment by evshi** [comment]
@sagardspeed2 it shouldn't break. This ticket is only about adding support for how the script is loaded into memory, not how it's evaluated.

**Comment by sagardspeed2** [comment]
@evshi, currently, the definition of the global block is like:

```
Global: |
  function callMeAsYouSee(){
    console.log("See ya, it works");
  }

  function manipulateData(dataArr){
    let newData = dataArr;
    console.log(dataArr);
  }
```

which holds this code in memory. Now, for the support of importing a script inside the global block, the definition of the global block will be:

```
Global:
  scriptName: test.js
```

So, during parsing of the ensemble app, we will import the script from the app context and store the script body inside the global block. Am I correct?

**Comment by evshi** [comment]
Yes correct

**Comment by sagardspeed2** [comment]
So, when I change the global block definition from string to scriptName, the previously defined global block will not have a scriptName, so previously defined YAML with the global block will not work.

**Comment by evshi** [comment]
No, it should support both, prefer the script name property if it exists, otherwise fallback to the plain string definition

**Comment by sagardspeed2** [comment]
@evshi Yup, I got it and I am doing this way only
