### ISSUE TITLE
Allow pass through of HTML attributes to node

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#293]
**Is your feature request related to a problem? Please describe.**
HTML attributes are important for browser compatibilty and accessibility. We should support allowing customers to set custom HTML attrs.

**Describe the solution you'd like**
Add a new property for `htmlAttributes` that will pass through to the HTML node.

**Describe alternatives you've considered**

**Additional context**

**Comment by sagardspeed2** [comment]
@evshi so I need to add this htmlAttributes in all existing widgets also. right ? like, button, avatar, Image, Card and so on.

**Comment by evshi** [comment]
Yeah you can effectively do this across widgets by adding a new hook in the use register bindings hook
