### ISSUE TITLE
Add support for Flow

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#415]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by evshi** [comment]
@sibteali786 yeah please link your PR to this ticket and close it after.

**Comment by sibteali786** [comment]
the PR was merged a week ago @evshi

**Comment by evshi** [comment]
@sibteali786 link your PR from this interface 
![image](https://github.com/EnsembleUI/ensemble-react/assets/4132143/54cb49ac-75dc-4c05-ade6-492f61f5dc9c)

Or let me know what the PR number was and I can link it.
