### ISSUE TITLE
Sidebar does not update highlight when navigating by path

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#450]
**Describe the bug**
The sidebar menu should highlight the current screen. This doesn't work if you navigate via url.

**To Reproduce**

1. Go to Atlas home
2. Click on row in grid
3. Notice how sidebar still highlights home

**Expected behavior**
Sidebar menu should match on path also

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sagardspeed2** [comment]
@evshi please check this one, when I am navigating through URL, the active item gets effected in sidebar

https://github.com/EnsembleUI/ensemble-react/assets/31651612/15fe866d-3170-4882-9622-2a986f0a8f82

**Comment by evshi** [comment]
@sagardspeed2 please see my reproduction steps in the ticket...very easy to reproduce on atlas. It has something to do with the new path attribute and inputs.

**Comment by sagardspeed2** [comment]
@evshi when I checked this issue as per your given reproduction team, I find that when we click on the row in datagrid, it navigate to `advocate/workflow` screen, but in the left sidebar menu, there is no any menu item with workflow .

![Image](https://github.com/EnsembleUI/ensemble-react/assets/31651612/46d70c22-f986-4699-a591-1e075e0b83ae)
