### ISSUE TITLE
Implement Divider widget with at least the same options as available in the schema

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble-react#50]
ACs:

- [ ] Implement existing Divider widget schema

Kitchen sink https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/4a893a2e-5bde-400c-b974-b25b497d31a5#

**Comment by sibteali786** [comment]
@evshi isnt it already there , i implemented it before our Friday demo ?
