### ISSUE TITLE
Render item-template inside search component value

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#588]
**Is your feature request related to a problem? Please describe.**
Sometimes the search key and presentation can differ. We already support rendering options via item-template but when a user selects something only the key gets rendered in the input.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sagardspeed2** [comment]
@evshi check this
https://github.com/ant-design/ant-design/issues/21882.

They are suggesting to use `Select` instead of `AutoComplete` for our use case.

**Comment by evshi** [comment]
@sagardspeed2 can you try out Select with show search attribute?
