### ISSUE TITLE
Support loading images from ensemble app assets

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#644]
**Is your feature request related to a problem? Please describe.**
Ensemble applications can bundle assets in their application package and load them from YAML

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kmahmood74** [comment]
@sagardspeed2 any update here?

**Comment by sagardspeed2** [comment]
@kmahmood74 Not yet, but will start work on this after #648 .
