### ISSUE TITLE
Disparity between Flutter version for Theme definition; Defining Styles under Theme not working

### ISSUE THREAD

**Issue by AidenTag** [EnsembleUI/ensemble-react#646]
**Describe the bug**
When defining the app Theme, defining a theme under "Themes:", and putting Styles under that theme does not work, the styles are not reflected in the app, whereas if you define Styles on its own, the styles are reflected in the app.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sagardspeed2** [comment]
@AidenTag Can you please add your desired YAML for theme here. So I can check that ?
