### ISSUE TITLE
Styling priority issues, styles defined under className not given priority over Widget name based styles

### ISSUE THREAD

**Issue by AidenTag** [EnsembleUI/ensemble-react#647]
the css specificity rules are as follows - 

```
A browser determines which CSS will be applied to selectors based on its weight. Among the selectors which determine specificity are as follows:

1. Id selector (#IdNam)
2. Classes, attributes and pseudo-classes
3. Elements and pseudo-elements
4. Universal (*)  selector
```
from - [here](https://blogs.halodoc.io/best-practices-that-we-follow-to-avoid-specificity-issues/#:~:text=CSS%20specificity%20rule&text=Below%20are%20the%20order%20of,These%20selectors%20has%20lowest%20priority.)

Classes should take higher precedence over Element level styles but they are not.

**Comment by sibteali786** [comment]
@AidenTag thanks for pointing out the issue however it would look better if you use an example here so it's easy for someone to understand the problem.

Other than that as per Title I had a question.  
Q: Why should local widget styles be of lesser priority than the className styles? As per what we know about Html and Css inline styles are preferred over styles using class names.

**Comment by kmahmood74** [comment]
@sibteali786 updated the description to make it clear
