### ISSUE TITLE
Add Card widget

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#65]
ACs:

- [ ] Add a new widget for Card styling
- [x] Use Card in GridView to demonstrate Embrace user management dashboard

![Image](https://github.com/EnsembleUI/ensemble-react/assets/4132143/7874cdc7-d30d-4a2a-b85a-250162bd7a39)

**Comment by sibteali786** [comment]
We can also have media as an object with properties like 
```yaml
media:
    src
    height
    width
    placeholder  // if there is no image to show, just show a placeholder here 


```

**Comment by evshi** [comment]
The Card widget should be much more flexible. Just allow it accept children so people can build their own layout inside. The main value is in the styling.
