### ISSUE TITLE
Implement PopupMenu

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#67]
ACs:

- Render a view that will trigger a menu
- Allow specifying actions

![Image](https://github.com/EnsembleUI/ensemble-react/assets/4132143/32bb7b7d-fbae-4171-888d-3eb002aeb4e3)

**Comment by sibteali786** [comment]
hey @evshi some questions
1. Do i have to implement a modal ? That can be opened using maybe a button like in ensemble as [here](https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/92a5b5f5-7278-404c-b2a4-9e6e27a57aab)
Please elaborate it a bit more if possible, thanks.

**Comment by evshi** [comment]
@sibteali786 there's an existing widget that defines the schema https://github.com/EnsembleUI/ensemble/blob/a86a8081cabdc76425a5652cb4bb726c1e74ac56/assets/schema/ensemble_schema.json#L852

1. You will have to implement a menu view, not a full screen modal. Please see the screenshot.
2. Yes you need to allow any type of ensemble action, according to the schema.

**Comment by sanaf1333** [comment]
@anserwaseem https://github.com/EnsembleUI/ensemble-react/blob/demo/embrace/packages/runtime/src/widgets/Dropdown.tsx
