### ISSUE TITLE
Assets are not rendering through assets variable, They can be uploaded but don't render through variable

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble-react#716]
Image Using Asset variable for source
![image](https://github.com/user-attachments/assets/ff6b23d1-e667-45bc-b287-16e15e6f2fdb)

Image using url for source
![image](https://github.com/user-attachments/assets/c38f86a3-7020-43db-bd2c-2ddca4d89e09)

**Comment by sagardspeed2** [comment]
<img width="945" alt="image" src="https://github.com/user-attachments/assets/83282231-d70a-445b-a5c3-df9d607ff561">

it will work with the merge of #718

**Comment by sagardspeed2** [comment]
closing in favor of #718
