### ISSUE TITLE
Support custom fonts

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#762]
**Is your feature request related to a problem? Please describe.**
Fonts are important part of branding and UX. Customers have the ability to upload their own fonts or reference open source fonts like google fonts.

**Describe the solution you'd like**
https://docs.ensembleui.com/theme-and-styling/custom-fonts

**Describe alternatives you've considered**

**Additional context**
EDL implemented in Flutter runtime: https://github.com/EnsembleUI/ensemble/issues/1505

**Comment by sagardspeed2** [comment]
@evshi 

Based on the solution mentioned in https://stackoverflow.com/questions/41676054/how-to-add-fonts-to-create-react-app-based-projects and the way Flutter Ensemble registers fonts in the pubspec.yaml file, we can simplify the process of adding custom fonts to our project.

If we place our index.css file in the public folder and add our fonts to the public folder as well, then register the fonts in index.css using the @font-face rule, we won’t need to make any additional changes to our implementation. The custom font family will automatically be supported in the theme file.

In index.css ( this will be moved to public folder, so fonts src path will also change according to that )
<img width="754" alt="image" src="https://github.com/user-attachments/assets/a1ced996-8e67-489f-b42a-f27785ab76b5">

In theme.yaml
<img width="442" alt="image" src="https://github.com/user-attachments/assets/21de7360-4d2c-4135-a02d-a06bdddb4fda">

I added fonts in public folder
<img width="329" alt="image" src="https://github.com/user-attachments/assets/666a03d4-b3ca-43b7-bb08-797cdb5c9800">

and here is the output
<img width="1237" alt="image" src="https://github.com/user-attachments/assets/180e17a7-1c23-440f-a370-c7117e24c3a4">

where the button us using the custom font family

**Comment by evshi** [comment]
@sagardspeed2 in ensemble fonts are fetched from firebase they aren't always built into the project. So you need to find a way to load fonts at runtime. Please discuss with @justEhmadSaeed
