### ISSUE TITLE
Require Drawer Widget for Mobile Responsive Websites 

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble-react#775]
- Following is the dashboard in which I am using this sidebar

![image](https://github.com/user-attachments/assets/560476a9-d0b3-4105-af3e-04345175f5fd)

- This is the mobile responsive design in which I am using Hamburger Button Icon shows the PopupMenu to list the Navbar Items
![image](https://github.com/user-attachments/assets/ab88579c-7242-4966-93d2-95c192c3b850)

Requirements:
- I need a drawer for the mobile responsive view.
- Drawer should behave in a way that when I click on Hamburger Icon, the Drawer should pop out from left to right as a sidebar but it should overlay the screen.

Example:
![image](https://github.com/user-attachments/assets/35739a2e-42b5-4a7a-85bb-044d03bd9a06)

**Comment by evshi** [comment]
@mehsaandev @jkorn8 the design you have added is not really a drawer - it can be easily implemented an icon with a popup menu. Note the full drawer pattern covers more of the page and has a mask. Which solution is what you're looking for?

Reference for existing ensemble drawer https://docs.ensembleui.com/screens-and-widgets/screen-structure#drawer

cc: @sagardspeed2
